"""
Data Catalog Metadata Extractor

Extracts technical metadata from a database table (schema, row count, sample data)
and produces a skeleton catalog entry in Markdown.

Requires: sqlalchemy (pip install sqlalchemy)
Supports: PostgreSQL, SQLite, any SQLAlchemy-compatible database.

Usage:
    python catalog_extractor.py --conn "sqlite:///my_db.db" --table orders --schema main
    python catalog_extractor.py --conn "postgresql://user:pass@host/db" \
        --table orders_fact --schema analytics --output catalog_draft.md
"""

import argparse
import sys
from datetime import datetime


def _try_import_sqlalchemy():
    try:
        import sqlalchemy
        return sqlalchemy
    except ImportError:
        return None


def extract_metadata(conn_string: str, table_name: str, schema: str = None) -> dict:
    """Extract technical metadata using SQLAlchemy inspection."""
    sa = _try_import_sqlalchemy()
    if sa is None:
        raise ImportError("sqlalchemy is required: pip install sqlalchemy")

    import pandas as pd

    engine = sa.create_engine(conn_string)
    inspector = sa.inspect(engine)

    columns_raw = inspector.get_columns(table_name, schema=schema)
    pk = inspector.get_pk_constraint(table_name, schema=schema)
    pk_cols = set(pk.get("constrained_columns", []))
    fks = inspector.get_foreign_keys(table_name, schema=schema)
    fk_cols = set(c for fk in fks for c in fk.get("constrained_columns", []))

    columns = []
    for col in columns_raw:
        columns.append({
            "name": col["name"],
            "type": str(col["type"]),
            "nullable": col.get("nullable", True),
            "primary_key": col["name"] in pk_cols,
            "foreign_key": col["name"] in fk_cols,
            "description": "",
        })

    qualified = f"{schema}.{table_name}" if schema else table_name
    with engine.connect() as conn:
        result = conn.execute(sa.text(f"SELECT COUNT(*) FROM {qualified}"))
        row_count = result.scalar()

    return {
        "table_name": table_name,
        "schema": schema or "default",
        "qualified_name": qualified,
        "extracted_at": datetime.utcnow().isoformat(),
        "row_count": row_count,
        "columns": columns,
    }


def render_markdown(meta: dict) -> str:
    lines = [
        f"# {meta['table_name']}",
        "",
        "## Overview",
        "",
        f"**Name:** `{meta['qualified_name']}`  ",
        f"**Type:** table  ",
        "**Domain:** [fill in]  ",
        "**Criticality:** [critical / high / medium / low]  ",
        "",
        "**Description:**  ",
        "[One sentence: what business process or entity does this table represent?]",
        "",
        "## Ownership",
        "",
        "- **Business Owner:** [name / team]",
        "- **Technical Owner:** [name / team]",
        "",
        "## Schema",
        "",
        f"**Row Count (at extraction):** {meta['row_count']:,}  ",
        f"**Extracted:** {meta['extracted_at']}  ",
        "",
        "| Column | Type | Nullable | Keys | Description |",
        "| --- | --- | --- | --- | --- |",
    ]

    for col in meta["columns"]:
        keys = []
        if col["primary_key"]:
            keys.append("PK")
        if col["foreign_key"]:
            keys.append("FK")
        lines.append(
            f"| {col['name']} | {col['type']} | {'Yes' if col['nullable'] else 'No'} "
            f"| {', '.join(keys) or '-'} | [description] |"
        )

    lines += [
        "",
        "## Data Quality",
        "",
        "- **Completeness:** [%]",
        "- **Freshness:** [last updated / refresh schedule]",
        "- **Known issues:** [none / list]",
        "",
        "## Lineage",
        "",
        "**Upstream sources:**",
        "- [source table or system]",
        "",
        "**Downstream consumers:**",
        "- [dashboard / report / model]",
        "",
        "## Access & Governance",
        "",
        "**Access level:** [public / restricted / confidential]  ",
        "**Sensitivity:** [none / PII / financial / health]  ",
        "**Compliance tags:** [SOX / GDPR / HIPAA / none]  ",
        "",
        "**Access instructions:**  ",
        "[How to request access]",
        "",
        "---",
        "",
        f"*Generated by catalog_extractor.py on {meta['extracted_at']}*",
    ]

    return "\n".join(lines)


def main():
    parser = argparse.ArgumentParser(description="Extract catalog metadata from a database table.")
    parser.add_argument("--conn", required=True, help="SQLAlchemy connection string")
    parser.add_argument("--table", required=True, help="Table name")
    parser.add_argument("--schema", default=None, help="Schema name")
    parser.add_argument("--output", default=None, help="Output markdown file")
    args = parser.parse_args()

    meta = extract_metadata(args.conn, args.table, args.schema)
    md = render_markdown(meta)

    if args.output:
        with open(args.output, "w", encoding="utf-8") as f:
            f.write(md)
        print(f"Catalog draft written to {args.output}")
    else:
        print(md)


if __name__ == "__main__":
    # Demo: generate a skeleton catalog entry from a static schema description
    demo_meta = {
        "table_name": "orders_fact",
        "schema": "analytics",
        "qualified_name": "analytics.orders_fact",
        "extracted_at": datetime.utcnow().isoformat(),
        "row_count": 1_250_000,
        "columns": [
            {"name": "order_id",    "type": "VARCHAR",   "nullable": False, "primary_key": True,  "foreign_key": False, "description": ""},
            {"name": "customer_id", "type": "INTEGER",   "nullable": False, "primary_key": False, "foreign_key": True,  "description": ""},
            {"name": "order_date",  "type": "TIMESTAMP", "nullable": False, "primary_key": False, "foreign_key": False, "description": ""},
            {"name": "total_amount","type": "DECIMAL",   "nullable": False, "primary_key": False, "foreign_key": False, "description": ""},
            {"name": "status",      "type": "VARCHAR",   "nullable": False, "primary_key": False, "foreign_key": False, "description": ""},
        ],
    }
    print(render_markdown(demo_meta))
